### ISSUE TITLE
Create a Google form for professors that want to opt in to the project

### ISSUE THREAD

**Issue by mizu-benrb** [rainbow-cards/rainbow-cards.github.io#10]
Create a Google form to facilitate adding more professors to the project.

Ask for information like:
- Milestones/achievements
- Projects they are working on or have worked on
- Hobbies and interests
- Favorite campus meal
- Fun fact about themselves
- How to contact them (e.g. email)

**Comment by johnserraon** [comment]
Completed: [https://forms.gle/RJjyfaoXvakZ6eQNA](https://forms.gle/RJjyfaoXvakZ6eQNA)
Can be used tentatively until the app progresses far enough to let professors create them on the website themselves
